export const GET_DEVELOPER = 'GET_DEVELOPER';
export const SET_DEVELOPER = 'SET_DEVELOPER';
export const SET_DEVELOPER_PROFILE_IMAGE = 'SET_DEVELOPER_PROFILE_IMAGE';
export const GET_DEVELOPER_PROFILE_IMAGE = 'GET_DEVELOPER_PROFILE_IMAGE';
export const SET_DEVELOPER_STATE_LOADING = 'SET_DEVELOPER_STATE_LOADING';
export const IS_DEVELOPER_STATE_LOADING = 'IS_DEVELOPER_STATE_LOADING';
