export const SET_DEVELOPER_EXPERIENCE = 'SET_DEVELOPER_EXPERIENCE';
export const GET_DEVELOPER_EXPERIENCE = 'GET_DEVELOPER_EXPERIENCE';
export const DELETE_DEVELOPER_EXPERIENCE = 'DELETE_DEVELOPER_EXPERIENCE';
export const GET_DEVELOPER_EXPERIENCE_BY_ID = 'GET_DEVELOPER_EXPERIENCE_BY_ID';
export const UPDATE_DEVELOPER_EXPERIENCE = 'UPDATE_DEVELOPER_EXPERIENCE';
