export const GET_DEVELOPER_PROJECT = 'GET_DEVELOPER_PROJECT';
export const SET_DEVELOPER_PROJECT = 'SET_DEVELOPER_PROJECT';
export const DELETE_DEVELOPER_PROJECT = 'DELETE_DEVELOPER_PROJECT';
export const GET_DEVELOPER_PROJECT_BY_ID = 'GET_DEVELOPER_PROJECT_BY_ID';
export const UPDATE_DEVELOPER_PROJECT = 'UPDATE_DEVELOPER_PROJECT';
