export const GET_SKILLS = 'GET_SKILLS';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_DEVELOPER_SKILLS = 'SET_DEVELOPER_SKILLS';
export const GET_DEVELOPER_SKILLS = 'GET_DEVELOPER_SKILLS';
